//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "action_resource_type"
)]
pub enum ActionResourceType {
    #[sea_orm(string_value = "user")]
    User,
    #[sea_orm(string_value = "post")]
    Post,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "oauth_provider")]
pub enum OauthProvider {
    #[sea_orm(string_value = "google")]
    Google,
    #[sea_orm(string_value = "github")]
    Github,
    #[sea_orm(string_value = "discord")]
    Discord,
    #[sea_orm(string_value = "x")]
    X,
    #[sea_orm(string_value = "microsoft")]
    Microsoft,
}
